# Generated by Django 3.2.16 on 2022-12-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221212_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteslist',
            options={'default_related_name': 'favorites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping', 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
