# Generated by Django 3.2.16 on 2022-12-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221220_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteslist',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
