# Generated by Django 3.2.16 on 2022-12-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221218_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='units_of_measurement',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='title',
            new_name='name',
        ),
    ]
